#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\sorceryskill.bof
BOFS = spiritlink.bof bloodmagic.bof willsurge.bof forcespike.bof \
       volatilefocus.bof damagemastery.bof \
       efficiency.bof soulandbodyone.bof

!include $(KODDIR)\kod.mak
