#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\expansionsettings.bof
BOFS = desertsettings.bof imbuesettings.bof equipmentsettings.bof

!include $(KODDIR)\kod.mak
