#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\expansionsettings.bof
BOFS = desertsettings.bof \
       imbuesettings.bof \
       equipmentsettings.bof \
       witcherysettings.bof \
       sorcerysettings.bof \
       banditrysettings.bof \
       elementaleffectssettings.bof

!include $(KODDIR)\kod.mak
