#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\itematt.bof
BOFS = weapatt.bof iacorptr.bof iadurabl.bof iatransc.bof \
                iashroud.bof iaengrav.bof iamisdir.bof iaselinf.bof \
                ianewdsc.bof iaappdsc.bof iaquest.bof iapkptr.bof \
		ialinked.bof iamade.bof iasoulbond.bof

!include $(KODDIR)\kod.mak
