#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\resist.bof
BOFS = resfire.bof resshock.bof rescold.bof resgood.bof \
	resevil.bof resacid.bof gort.bof resmagic.bof

!include $(KODDIR)\kod.mak
