#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\staticgem.bof
BOFS = starfirediamond.bof sapphireteardrop.bof emeraldleaf.bof amberdisc.bof \
       blackpearl.bof jadeprism.bof blazingtourmaline.bof \
       quicksilvernodule.bof azuritebijou.bof glimmeringmoonstone.bof

!include $(KODDIR)\kod.mak