#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomatt.bof
BOFS = survivalroomatt.bof chaosroomatt.bof frenzyroomatt.bof \
       anonroomatt.bof invasionroomatt.bof

!include $(KODDIR)\kod.mak