#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\hex.bof
BOFS = vulnerability.bof \
       frailty.bof \
       humility.bof \
       corruption.bof \
       leeches.bof \
       barbs.bof \
       slow.bof

!include $(KODDIR)\kod.mak
