#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\hex.bof
BOFS = vulnerability.bof \
       frailty.bof \
       humility.bof \
       corruption.bof \
       slow.bof \
       flammability.bof \
       conductivity.bof \
       algidity.bof \
       corrosion.bof \
       fester.bof \
       mute.bof \
       weaken.bof \
       exhaustion.bof \
       bestill.bof \
       becloud.bof \
       blackmantle.bof \
       drain.bof

!include $(KODDIR)\kod.mak
