#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\resistanceradius.bof
BOFS = resradiusfire.bof resradiuscold.bof resradiusshock.bof \
       resradiusacid.bof

!include $(KODDIR)\kod.mak
