#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomench.bof
BOFS = martyrs.bof \
       darkness.bof \
       heat.bof killing.bof light.bof \
       silence.bof forceslt.bof

!include $(KODDIR)\kod.mak
