#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomench.bof
BOFS = martyrs.bof \
       darkness.bof \
       killing.bof \
       light.bof \
       forceslt.bof \
       silence.bof

!include $(KODDIR)\kod.mak
