#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\teleportspell.bof
BOFS = elusion.bof rescue.bof deathrift.bof blink.bof guildhallrecall.bof

!include $(KODDIR)\kod.mak
