#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\desertafterlife.bof

BOFS = desertaldunes1.bof desertaldunes2.bof desertaldunes3.bof \
       desertaldunes4.bof

!include $(KODDIR)\kod.mak
