#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\multicst.bof
BOFS = hunt.bof shttrlck.bof summcow.bof bond.bof shadrift.bof \
       oldbldinher.bof

!include $(KODDIR)\kod.mak
