#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\witcheryskill.bof
BOFS = arcaneknowledge.bof \
       rotememorization.bof \
       efficientcasting.bof \
       ancientpact.bof \
       unhallowedrunes.bof \
       bloodrunes.bof \
       ostracization.bof

!include $(KODDIR)\kod.mak
