#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\witchery.bof
BOFS = arcaneknowledge.bof \
       rotememorization.bof \
       efficientcasting.bof \
       ancientpact.bof

!include $(KODDIR)\kod.mak
