#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\radiusench.bof
BOFS = umbrella.bof antimag.bof winds.bof sandstor.bof truce.bof jala.bof \
       primalrestorat.bof blur.bof resistanceradius.bof

!include $(KODDIR)\kod.mak
