#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\radiusench.bof
BOFS = antimag.bof \
       jala.bof \
       sandstor.bof \
       truce.bof \
       umbrella.bof \
       winds.bof \
       heat.bof \
       bane.bof

!include $(KODDIR)\kod.mak
