#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\damagemastery.bof
BOFS = devotion.bof energy.bof entropy.bof intensity.bof lethality.bof

!include $(KODDIR)\kod.mak
