#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\banditry.bof
BOFS = awareness.bof sneak.bof hide.bof stance.bof tumble.bof backstab.bof spy.bof perception.bof

!include $(KODDIR)\kod.mak
